# Generated by Django 2.1.5 on 2019-02-22 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20190221_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_img', models.ImageField(default='projects_pics/nopic.jpeg', upload_to='multi/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
    ]
